-- Create quotes table if it doesn't exist
create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  text text not null,
  author text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.quotes enable row level security;

-- Policies
create policy "Public quotes are viewable by everyone"
  on public.quotes for select
  using ( true );

create policy "Authenticated users can insert quotes"
  on public.quotes for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update quotes"
  on public.quotes for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete quotes"
  on public.quotes for delete
  using ( auth.role() = 'authenticated' );
