-- Create the likes table
create table likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, image_url)
);

-- Enable Row Level Security
alter table likes enable row level security;

-- Policy: Users can view all likes (to see counts)
create policy "Likes are visible to everyone"
  on likes for select
  using ( true );

-- Policy: Users can insert their own likes
create policy "Users can insert their own likes"
  on likes for insert
  with check ( auth.uid() = user_id );

-- Policy: Users can delete their own likes
create policy "Users can delete their own likes"
  on likes for delete
  using ( auth.uid() = user_id );

-- Create the quotes table
create table quotes (
  id bigint generated by default as identity primary key,
  text text not null,
  author text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table quotes enable row level security;

-- Policy: Quotes are visible to everyone
create policy "Quotes are visible to everyone"
  on quotes for select
  using ( true );

-- Create the quote_likes table
create table quote_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  quote_id bigint references quotes(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, quote_id)
);

-- Enable Row Level Security
alter table quote_likes enable row level security;

-- Policy: Users can view all quote likes
create policy "Quote likes are visible to everyone"
  on quote_likes for select
  using ( true );

-- Policy: Users can insert their own quote likes
create policy "Users can insert their own quote likes"
  on quote_likes for insert
  with check ( auth.uid() = user_id );

-- Policy: Users can delete their own quote likes
create policy "Users can delete their own quote likes"
  on quote_likes for delete
  using ( auth.uid() = user_id );
